# Generated by Django 5.1.6 on 2025-02-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventographer_App', '0006_alter_customer_reset_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='reset_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
