# Generated by Django 5.1.6 on 2025-02-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventographer_App', '0008_remove_customer_token_alter_customer_reset_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='reset_token',
        ),
        migrations.AddField(
            model_name='customer',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
