# Generated by Django 5.1.6 on 2025-02-28 06:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventographer_App', '0009_remove_customer_reset_token_customer_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='reset_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
