# Generated by Django 5.1.6 on 2025-02-28 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventographer_App', '0010_customer_reset_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='reset_token',
        ),
    ]
