# Generated by Django 5.1.6 on 2025-02-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_token_alter_customuser_login_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='login_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
